owner: tyrepharm
repo: upptime-test

sites:
  - name: (dev) Tyre Pharmacy
    url: $DEVELOPMENT_TYREPHARM/
  - name: (dev) Monitor / MySQL 
    url: $DEVELOPMENT_TYREPHARM/local/api/Monitor/db
    headers:
      - "Content-Type: application/json"
  - name: (dev) Monitor / init.php 
    url: $DEVELOPMENT_TYREPHARM/local/api/Monitor/init
    headers:
      - "Content-Type: application/json"
  - name: (dev) Monitor / services 
    url: $DEVELOPMENT_TYREPHARM/local/api/Monitor/services
    headers:
      - "Content-Type: application/json"


status-website:
  baseUrl: /upptime-test
  name: (test) Upptime
  logoUrl: https://tyrepharm.ru/upload/aspro.mshop/145/14547cf839786595aaf89f08fb31a9ca.svg